### ISSUE TITLE
Support for arm/arm64 arch (many Single Board Computers)

### ISSUE THREAD

**Issue by stdevPavelmc** [jadolg/DockerImageSave#12]
Almost all single board computers (SBC) like the famous Raspberry Pi are arm, but more moderns like the Orange Pi ones can support the arm64 arch.

Having this tool on arm/arm64 will help to support the SBC market.

**Comment by jadolg** [comment]
Fixed in d897312f2c37f78c744ec147c28e3f7e5eacf51f
The first release for arm platforms on Linux is https://github.com/jadolg/DockerImageSave/releases/tag/1.5.2

**Comment by jadolg** [comment]
By the way, if installing from snap, you can use much more architectures as their system compiles automagically for a bunch of them
