### ISSUE TITLE
Nuevas opciones a implementar

### ISSUE THREAD

**Issue by danny920825** [jadolg/DockerImageSave#13]
Seria bueno eliminar el servicio de cache, al final no es que todo el mundo baje la misma imagen en el dia. El programa deberia al terminar de descargar, eliminar la imagen del servidor. Tanto el comprimido como de docker del pull.
Esto no se aplica si se utiliza el metodo --no-download obviamente...
Lo otro seria agregarle la opcion --load la cual al terminar de descargar la imagen la cargue en el host si tiene docker instalado.

**Comment by jadolg** [comment]
El problema con la caché es que no puedo determinar cuándo un fichero se "termina" de descargar. La idea es que puedas descargarlo en pedazos y en varios días incluso si hace falta por lo que asumir que se puede borrar algo en cualquier momento no va a estar bien. Tengo que pensar en una solución más genérica y que no dañe el proceso, así que por el momento hay que usar los tags lo más atómicos posibles.
