### ISSUE TITLE
Replace the : caracter on the images with a _

### ISSUE THREAD

**Issue by jadolg** [jadolg/DockerImageSave#5]

**Comment by ragnarok22** [comment]
This is a great issue. On Windows the tar.zip file has problems. This is downloaded correctly but windows don't recognizes the file therefore don't let unzip it

**Comment by ragnarok22** [comment]
But if you downloaded manually using the API the file is download correctly

**Comment by jadolg** [comment]
Maybe I could change only the download code on the client for it to work properly.
I need to fix it anyway because for some reason downloads are not being resumed and that's a big issue.

**Comment by jadolg** [comment]
should be fixed on 1.5.
I tested it on Linux and it works like charm. Would you please try to use it on Windows @ragnarok22 ?
