### ISSUE TITLE
Error response from daemon: manifest not found: manifest unknown

### ISSUE THREAD

**Issue by mrbrazzi** [jadolg/DockerImageSave#9]
I try to download the Docker image and got the following error message:
```
PS D:\> docker pull guamulo/dockerimagesave
Using default tag: latest
Error response from daemon: manifest for guamulo/dockerimagesave:latest not found: manifest unknown: manifest unknown
PS D:\>
```

**Comment by jadolg** [comment]
Yeah, I'm not pushing any `latest` tag.
Maybe I should add it to the CI

**Comment by jadolg** [comment]
I just added the CI code so I always push the image tagged also as latest when deploying and it is already a version on dockerhub.
Please check and reopen again this issue if it still fails.
